package ittapiros;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kalac
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1pohar = new javax.swing.JButton();
        j2pohar = new javax.swing.JButton();
        j3pohar = new javax.swing.JButton();
        jvalasz = new javax.swing.JLabel();
        jujhely = new javax.swing.JCheckBox();
        jmegoldas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jujjatek = new javax.swing.JMenuItem();
        jmentes = new javax.swing.JMenuItem();
        jbetoltes = new javax.swing.JMenuItem();
        j3poharasjatek = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        j4poharasjatek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j1pohar.setText("1 pohár");

        j2pohar.setText("2 pohár");

        j3pohar.setText("3 pohár");

        jujhely.setText("új helyre rakás");

        jmegoldas.setText("Megoldás:");

        jMenu1.setText("Fájl");

        jujjatek.setText("új játék");
        jMenu1.add(jujjatek);

        jmentes.setText("mentés");
        jMenu1.add(jmentes);

        jbetoltes.setText("betöltés");
        jMenu1.add(jbetoltes);

        jMenuBar1.add(jMenu1);

        j3poharasjatek.setText("Játék");

        jMenuItem4.setText("3 pohár");
        j3poharasjatek.add(jMenuItem4);

        j4poharasjatek.setText("4 pohár");
        j4poharasjatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4poharasjatekActionPerformed(evt);
            }
        });
        j3poharasjatek.add(j4poharasjatek);

        jMenuBar1.add(j3poharasjatek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j1pohar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(j2pohar)
                        .addGap(32, 32, 32)
                        .addComponent(j3pohar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jvalasz, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jujhely))
                            .addComponent(jmegoldas))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1pohar)
                    .addComponent(j2pohar)
                    .addComponent(j3pohar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmegoldas)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jujhely)
                    .addComponent(jvalasz, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j4poharasjatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4poharasjatekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4poharasjatekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j1pohar;
    private javax.swing.JButton j2pohar;
    private javax.swing.JButton j3pohar;
    private javax.swing.JMenu j3poharasjatek;
    private javax.swing.JMenuItem j4poharasjatek;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jbetoltes;
    private javax.swing.JLabel jmegoldas;
    private javax.swing.JMenuItem jmentes;
    private javax.swing.JCheckBox jujhely;
    private javax.swing.JMenuItem jujjatek;
    private javax.swing.JLabel jvalasz;
    // End of variables declaration//GEN-END:variables
}
